### ISSUE TITLE
More precise handling of broken links

### ISSUE THREAD

**Issue by yuliya-ivaniukovich** [veraPDF/verapdf-crawler#89]
At the moment we try to download and parse all the documents with one of the following criteria:

- having one of extensions: pdf, odt, ods, odp, doc, docx, xls, xlsx, ppt, pptx
- having one of corresponsing Content-Type headers

As a result we have a number of links to e.g. already archived documents which are failing with error like 'End Of File reached'.
It would be better to detect such links earlier and do not include them into results.

Proposal:
we should at least exclude HTML and plain text response types from the results.

**Comment by BezrukovM** [comment]
fixed by https://github.com/veraPDF/verapdf-crawler/pull/93
